# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(default='No description.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(default='http://placehold.it/150x80?text=IMAGE'),
        ),
    ]
